### ISSUE TITLE
Log is spammed with a "calling /alive" message every few seconds

### ISSUE THREAD

**Issue by itaymaoz-lama** [osskit/dafka-producer-helm-chart#21]
I think these log messages don't add anything and have no value, we should probably remove them

![image](https://user-images.githubusercontent.com/105851002/177180035-e76d73b4-c362-466d-a549-3424efde873a.png)

**Comment by guysegal** [comment]
yeah, this should definitely be removed

**Comment by guysegal** [comment]
fixed
